//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPet
{
    using System;
    using System.Collections.Generic;
    
    public partial class boleta
    {
        public boleta()
        {
            this.detalle_boleta = new HashSet<detalle_boleta>();
        }
    
        public int NUMERO { get; set; }
        public string DNI { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public Nullable<decimal> BRUTOS { get; set; }
        public Nullable<decimal> DESCUENTO { get; set; }
        public Nullable<decimal> IGV { get; set; }
        public Nullable<decimal> VALOR_VENTA { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual ICollection<detalle_boleta> detalle_boleta { get; set; }
    }
}
