//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPet
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita
    {
        public int ID { get; set; }
        public string CODIGO_MEDICO { get; set; }
        public string DNI_CLIENTE { get; set; }
        public Nullable<int> ID_MASCOTA { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string HORA { get; set; }
        public Nullable<int> ESTADO { get; set; }
    
        public virtual mascota mascota { get; set; }
        public virtual medico medico { get; set; }
        public virtual cliente cliente { get; set; }
    }
}
