//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPet
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.mascota = new HashSet<mascota>();
        }
    
        public string id_cliente { get; set; }
        public string email { get; set; }
        public string contrasena { get; set; }
        public string nombre { get; set; }
        public string apellidoPat { get; set; }
        public string apellidoMat { get; set; }
        public string dni { get; set; }
        public string id_sexo { get; set; }
        public string id_pais { get; set; }
        public string id_ciudad { get; set; }
        public string id_distrito { get; set; }
        public string direccion { get; set; }
        public string referencia_direccion { get; set; }
        public string telefono { get; set; }
        public string tipo_usuario { get; set; }
    
        public virtual ciudad ciudad { get; set; }
        public virtual distrito distrito { get; set; }
        public virtual pais pais { get; set; }
        public virtual sexo sexo { get; set; }
        public virtual tipo_usuario tipo_usuario1 { get; set; }
        public virtual ICollection<mascota> mascota { get; set; }
    }
}
