//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPet
{
    using System;
    using System.Collections.Generic;
    
    public partial class historia_clinica
    {
        public string DNI_CLIENTE { get; set; }
        public int ID_MASCOTA { get; set; }
        public int ID { get; set; }
        public Nullable<int> CITA { get; set; }
        public Nullable<int> RECETA { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual mascota mascota { get; set; }
    }
}
