//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPet
{
    using System;
    using System.Collections.Generic;
    
    public partial class mascota
    {
        public mascota()
        {
            this.cita = new HashSet<cita>();
            this.historia_clinica = new HashSet<historia_clinica>();
        }
    
        public string DNI { get; set; }
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> ID_ESPECIE { get; set; }
        public Nullable<int> ID_RAZA { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
    
        public virtual ICollection<cita> cita { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual especie especie { get; set; }
        public virtual ICollection<historia_clinica> historia_clinica { get; set; }
        public virtual raza raza { get; set; }
    }
}
