//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPet
{
    using System;
    using System.Collections.Generic;
    
    public partial class mascota
    {
        public string id_mascota { get; set; }
        public string nombre_mascota { get; set; }
        public string fecha_nac { get; set; }
        public string id_raza { get; set; }
        public string id_tamaño { get; set; }
        public string id_cliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual raza raza { get; set; }
        public virtual tamaño tamaño { get; set; }
    }
}
