//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPet
{
    using System;
    using System.Collections.Generic;
    
    public partial class medico
    {
        public medico()
        {
            this.cita = new HashSet<cita>();
        }
    
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public Nullable<int> ID_ESPECIALIDAD { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
    
        public virtual ICollection<cita> cita { get; set; }
        public virtual especialidad especialidad { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
