//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mypetEntities : DbContext
    {
        public mypetEntities()
            : base("name=mypetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ciudad> ciudad { get; set; }
        public DbSet<cliente> cliente { get; set; }
        public DbSet<distrito> distrito { get; set; }
        public DbSet<mascota> mascota { get; set; }
        public DbSet<pais> pais { get; set; }
        public DbSet<raza> raza { get; set; }
        public DbSet<sexo> sexo { get; set; }
        public DbSet<tamaño> tamaño { get; set; }
        public DbSet<tipo_usuario> tipo_usuario { get; set; }
    }
}
