//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mypetEntities : DbContext
    {
        public mypetEntities()
            : base("name=mypetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<boleta> boleta { get; set; }
        public DbSet<cita> cita { get; set; }
        public DbSet<cliente> cliente { get; set; }
        public DbSet<detalle_boleta> detalle_boleta { get; set; }
        public DbSet<especialidad> especialidad { get; set; }
        public DbSet<especie> especie { get; set; }
        public DbSet<estado> estado { get; set; }
        public DbSet<historia_clinica> historia_clinica { get; set; }
        public DbSet<mascota> mascota { get; set; }
        public DbSet<medico> medico { get; set; }
        public DbSet<producto> producto { get; set; }
        public DbSet<raza> raza { get; set; }
        public DbSet<sexo> sexo { get; set; }
        public DbSet<tabla_postal> tabla_postal { get; set; }
        public DbSet<tipo_usuario> tipo_usuario { get; set; }
        public DbSet<usuario> usuario { get; set; }
        public DbSet<variables> variables { get; set; }
    }
}
