//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPet
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public producto()
        {
            this.detalle_boleta = new HashSet<detalle_boleta>();
        }
    
        public string CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> STOCK_ACTUAL { get; set; }
        public Nullable<int> STOCK_DISPONIBLE { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
    
        public virtual ICollection<detalle_boleta> detalle_boleta { get; set; }
    }
}
