//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPet
{
    using System;
    using System.Collections.Generic;
    
    public partial class sexo
    {
        public sexo()
        {
            this.cliente = new HashSet<cliente>();
        }
    
        public string id_sexo { get; set; }
        public string descrip_sexo { get; set; }
    
        public virtual ICollection<cliente> cliente { get; set; }
    }
}
