//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPet
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<int> TIPO_USUARIOS { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual estado estado1 { get; set; }
        public virtual medico medico { get; set; }
        public virtual tipo_usuario tipo_usuario { get; set; }
    }
}
